### PR TITLE
Fix no root config issue

### LINKED ISSUE #108: Disable option not preventing sass-lint from linting files
I'm working on a project where I need `sass-lint` to be disabled because the team is using `stylelint` instead. I'm having trouble getting it to disable. There is no `.sass-lint.yml` set in my project root.
- Atom version: 1.8.0
- linter-sass-lint version: 1.6.1
- Global sass-lint version (if used): N/A
- Platform:
  - [ X ] OSX
  - [ ] Windows
  - [ ] Linux
- Expected behaviour: 

Flagging the checkbox "Disable when no sass-lint config file is found in your project root" should disable linting:

- Actual behaviour / issue description:

sass-lint is still being triggered. Have tried restarting Atom, etc. to no avail.

### PR DESCRIPTION
**Pull request by DanPurdy**
The issue raised in #108 has 2 paths to take, originally it was meant to follow the linter-eslint style of config resolution and the disable option would disable if it couldn't be found. However when setting it up and modifying it the description has become unclear and suggests that if a config file doesn't exist in the root of your atom project then linter-sass-lint should be disabled.

This PR looks for the root of your project and checks to see if a config file exists there and is readable. It will only take affect if you've specified that the no config root disable option is true otherwise we keep the functionality we have now where we search for a config file.

In version 2 of this plugin I will remove this and follow the linter-eslint style config resolution as I feel this root config check is a bit of a hack..

Currently in progress..

Closes #108

### CODE REVIEW

File: lib/main.coffee [hunk 1]
```diff
@@ -68,6 +67,8 @@ module.exports =
   findExecutable: ->
     {spawnSync} = require 'child_process'
     consistentEnv = require 'consistent-env'
+    path = require 'path'
```
Comment (Arcanemagus) [inline lib/main.coffee]: Instead of `require`ing it every time, leave `path` in the global and just check if it's been required already before `require`ing it.

```coffeescript
path = null
# ...
findExecutable: ->
  path = require 'path' if not path?
# ...
provideLinter: ->
  path = require 'path' if not path?
```

File: lib/helpers.coffee [hunk 2]
```diff
@@ -33,3 +33,53 @@ module.exports =
...
+      try
+        fs.accessSync(rootDir, fs.R_OK)
+        return rootDir
+      catch
+        return null
+
+    return rootDir
+
+  ###*
+   * Looks for an returns the path to a projects config file or null if it can't be found or doesn't exist
```
Comment (Arcanemagus) [inline lib/helpers.coffee]: `for an returns` -> `for and returns`

File: lib/helpers.coffee [hunk 3]
```diff
@@ -33,3 +33,53 @@ module.exports =
...
+   * @param {Object} editor - An editor instance
+   * @param {string} filePath - The currently active editor file path
+   * @param {string} configExt - The Sass-lint config extension
+   * @param {boolean} noRootConfigDisable - The user specified option to disable linter-sass-lint if no config
```
Comment (Arcanemagus) [inline lib/helpers.coffee]: `noRootConfigDisable` -> `noRootConfDisable` (or fix it below to match this)

File: lib/helpers.coffee [hunk 4]
```diff
@@ -33,3 +33,53 @@ module.exports =
...
+   ###
+  getRootDir: (filePath) ->
+    rootDir = null
+    atom.project.rootDirectories.forEach((dir) ->
+      if dir.contains(filePath) then rootDir = dir
+    )
+    return rootDir
+
+  ###*
+   * Checks to see if a config file exists in the projects root directory if a root directory exists
```
Comment (Arcanemagus) [inline lib/helpers.coffee]: * `projects` -> `project's`

File: lib/helpers.coffee [hunk 5]
```diff
@@ -33,3 +33,53 @@ module.exports =
...
+   * @param {string|null} dir - The current project root or null if a project doesn't exist
+   * @param {string} configExt - The Sass-lint config extension
+   * @return {string|null} The path to the config file if located in the project root, null if it doesn't exist
+   ###
+  getRootDirConfig: (dir, configExt) ->
+    fs = require 'fs'
+    rootDir = dir
+
+    if rootDir
+      rootDir = rootDir.getPath() + '/' + configExt
```
Comment (Arcanemagus) [inline lib/helpers.coffee]: Shouldn't this just be `rootDir`? Also use `path.join()` instead of concatenating in a `/` manually.

File: lib/helpers.coffee [hunk 6]
```diff
@@ -33,3 +33,53 @@ module.exports =
...
     return existingSyntax
+
+  ###*
+   * Attempts to resolve the root directory/project directory of the currently open file/editor instance
+   * @param {string} filePath - The currently active editor file path
+   * @return {Object|null} The project directory instance or null if no project root is found
+   ###
+  getRootDir: (filePath) ->
+    rootDir = null
+    atom.project.rootDirectories.forEach((dir) ->
```
Comment (Arcanemagus) [inline lib/helpers.coffee]: This can all be replaced with:
```coffeescript
atom.project.relativizePath(filePath)[0]
```

It returns the project path as Atom sees it, or `null` if it isn't open in a project.

**Comment by Arcanemagus** [comment]
That's all I see for now, sorry it took so long to get to this, was dealing with `eslint` updates everywhere!

File: lib/helpers.coffee (hunk 6 above)
Comment (DanPurdy) [inline lib/helpers.coffee]: I was having issues when multiple projects were open in one window though. I'll double check again though.

**Comment by DanPurdy** [comment]
@Arcanemagus don't worry about it, Im not completely finished yet, I just wanted to run this through the different CI platforms to see what was going on. Thanks for taking the time to look through it! 👍

File: lib/helpers.coffee [hunk 7]
```diff
@@ -33,3 +33,49 @@ module.exports =
...
+   * @param {boolean} noRootConfDisable - The user specified option to disable linter-sass-lint if no config
+   *                 is found in the root of the project
+   * @return {string|null} The path to the config file or null if not found
+   ###
+  getConfig: (editor, filePath, configExt, noRootConfDisable) ->
+    {find} = require 'atom-linter'
+    rootDir = @getRootDir(filePath)
+    rootDirConfig = @getRootDirConfig(rootDir, configExt)
+
+    if noRootConfDisable is true and rootDirConfig is false then return null
```
Comment (Arcanemagus) [inline lib/helpers.coffee]: Did you mean `rootDirConfig?`? `getRootDirConfig` returns a string or `null`, not `false`.

Comment (DanPurdy) [inline lib/helpers.coffee]: Probably, i've not had much time recently to look into any OS work. Hopefully that will change soon but I've not merged this yet as I really want to be sure it solves the issue people were having.
